version: '3.5'

services:
  db:
    container_name: influx_db
    image: influxdb:1.8.3
    restart: always
    ports:
      - 8086:8086
    environment:
      INFLUXDB_HTTP_FLUX_ENABLED: "true"

  api:
    container_name: v-api
    build:
      context: ..
    restart: always
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 8086
      CALCULATE_API_HOST: vcalculateapi
      CALCULATE_API_PORT: 5000

      GUNICORN_LOG_LEVEL: debug
      GUNICORN_WORKER_CLASS: sync
      GUNICORN_WORKER_CONNECTIONS: 1000
      GUNICORN_WORKERS: 1
      GUNICORN_LIMIT_REQUEST_LINE: 4094
      GUNICORN_TIMEOUT: 60

networks:
  default:
    name: v-app